DROP TABLE IF EXISTS EVENTS;

CREATE TABLE EVENTS (
	ICALUID VARCHAR(100) NOT NULL PRIMARY KEY,	
	STARTDATE DATE, 
	STARTDATETIME DATETIME,
	SUMMARY VARCHAR(200) NOT NULL,
    LOCATION VARCHAR(80),    
    FACEBOOKLINK VARCHAR(200),
    TICKETPURCHASELINK VARCHAR(200),
    FLYERURL VARCHAR(200),
    VISIBILITY VARCHAR(20),
    SEQUENCE INTEGER NOT NULL,    
    CREATED DATETIME NOT NULL,
    UPDATED DATETIME NOT NULL,
    CREATOR VARCHAR(200) NOT NULL
    
);