DROP TABLE EVENTS;

CREATE TABLE EVENTS (
	ID MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CALENDARSUMMARY VARCHAR(200) NOT NULL,	
	CALENDARICALUID VARCHAR(100) NOT NULL UNIQUE,	
	CALENDARSTART DATETIME NOT NULL,
    CALENDARLOCATION VARCHAR(80),
    LOCATION VARCHAR(80),
    SUMMARY VARCHAR(200),
    DESCRIPTION VARCHAR(200),
    CHANGED BOOLEAN DEFAULT TRUE,
    VISIBLE BOOLEAN DEFAULT FALSE,
    CREATED TIMESTAMP NOT NULL,
    UPDATED TIMESTAMP NOT NULL,
    FACEBOOKLINK VARCHAR(200),
    TICKETPURCHASELINK VARCHAR(200)
);